# *BULANIK MANTIK ve PYTHON UYGULAMALARI* - Öğr. Gör Ali ÇETİNKAYA

***ISBN: *** 978-605-4827-98-5

## **Bölüm 2.3.1. Örnek Python Kod Uygulaması**


In [1]:
# Örnek Kod 1 çalışması: Numpy Dizi Uygulaması!

import numpy as np # numpy kütüphanesini Python dosyasına çektik.
dizi_1 = np.array([1,2,3,4,5,6,7,8,9]) # birinci dizi ve elemanları
dizi_2 = np.array([[1,2,9],[3,4,6]]) # ikinci dizi ve elemanları
print(dizi_1.shape) # Birinci dizinin eleman sayısını yazdırma 
print(dizi_2.shape , "elemanlı") # İkinci dizinin eleman sayısını yazdırma 
print(dizi_1.dtype.name) # birinci dizinin eleman tipini yazdırma
print(dizi_2.dtype.name) # İkinci dizinin eleman tipini yazdırma
sifir_dizisi = np.zeros((3,4))
print(sifir_dizisi) # 3x4 boyutlu elemanlarının 0 olan bir dizi oluşur.
bir = np.ones((3,3))
print(bir) # 3x3 boyutlu tüm elemanlarının “1” olan dizi oluşturulmuştur.


(9,)
(2, 3) elemanlı
int64
int64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Kitabın Bulunduğu Sayfalar:

https://www.pandora.com.tr/kitap/bulanik-mantik-ve-python-uygulamalari/853298

https://www.kitapyurdu.com/kitap/bulanik-mantik-ve-python-uygulamalari/644153.html 

https://www.dr.com.tr/Kitap/Bulanik-Mantik-ve-Python-Uygulamalari/Egitim-Basvuru/Bilgisayar/urunno=0002035935001

https://kddb.gelisim.edu.tr/tr/idari-duyuru-igu-yayinlarindan-106-kitap-bulanik-mantik-ve-python-uygulamalari 


